[package]
name = "github-bot"
version = "0.1.0"
authors = ["DeltaChatBot Contributers<https://github.com/deltachat-bot>"]
edition = "2021"

[dependencies]
anyhow = "^1.0"
deltachat = { git = "https://github.com/deltachat/deltachat-core-rust"}
tokio = { version = "^1.21", features = ["rt-multi-thread", "macros", "signal"]}
tide = "^0.16"
clap = {version="^4.0", features=["derive", "cargo"]}
serde_json = "^1.0"
serde = "^1.0"
thiserror="^1.0"
log = "^0.4"
env_logger = "0.10.0"
surrealdb = "1.0.0-beta.8"
strum_macros = "^0.24"
reqwest = "^0.11"
itertools = "^0.10"
pnet = "*"